add:
    pattern: /wiki/add
    defaults: { _controller: WikiMainBundle:Default:add }

edit:
    pattern: /wiki/edit/{alias}
    defaults: { _controller: WikiMainBundle:Default:edit }
    requirements:
        page: alias \d+

show:
    pattern:  /wiki/{alias}
    defaults: { _controller: WikiMainBundle:Default:show }
    requirements:
        page: alias \w+

page-delete:
    pattern:  /page-delete/{alias}
    defaults: { _controller: WikiMainBundle:Default:delete }

homepage:
    pattern:  /wiki
    defaults: { _controller: WikiMainBundle:Default:index }