

add:
    pattern: /add
    defaults: { _controller: WikiMainBundle:Default:add }

edit:
    pattern: /edit/{alias}
    defaults: { _controller: WikiMainBundle:Default:edit }
    requirements:
        page: alias \w+

show:
    pattern:  /{alias}
    defaults: { _controller: WikiMainBundle:Default:show }
    requirements:
        page: alias \w+


page-delete:
    pattern:  /page-delete/{alias}
    defaults: { _controller: WikiMainBundle:Default:delete }

homepage:
    pattern:  /
    defaults: { _controller: WikiMainBundle:Default:index }